// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEnsRVtO87qDd-JLeU-qUsRYblk7gqVd4',
    appId: '1:152645354927:web:7a6d091e159bdc3808db5a',
    messagingSenderId: '152645354927',
    projectId: 'qlchitieu-30b85',
    authDomain: 'qlchitieu-30b85.firebaseapp.com',
    storageBucket: 'qlchitieu-30b85.firebasestorage.app',
    measurementId: 'G-B7FBH3RBK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmjRcpakGC6N4MamfO1xrUEtQyN62gank',
    appId: '1:152645354927:android:bb7018bca02a7afd08db5a',
    messagingSenderId: '152645354927',
    projectId: 'qlchitieu-30b85',
    storageBucket: 'qlchitieu-30b85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPv7Ov_yHCzuIV_WCAu9JQp-ERFXFRO44',
    appId: '1:152645354927:ios:4e9d7837d5c52c2408db5a',
    messagingSenderId: '152645354927',
    projectId: 'qlchitieu-30b85',
    storageBucket: 'qlchitieu-30b85.firebasestorage.app',
    iosBundleId: 'com.example.quanlychitieu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPv7Ov_yHCzuIV_WCAu9JQp-ERFXFRO44',
    appId: '1:152645354927:ios:4e9d7837d5c52c2408db5a',
    messagingSenderId: '152645354927',
    projectId: 'qlchitieu-30b85',
    storageBucket: 'qlchitieu-30b85.firebasestorage.app',
    iosBundleId: 'com.example.quanlychitieu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCEnsRVtO87qDd-JLeU-qUsRYblk7gqVd4',
    appId: '1:152645354927:web:e6b5c1235cf768f508db5a',
    messagingSenderId: '152645354927',
    projectId: 'qlchitieu-30b85',
    authDomain: 'qlchitieu-30b85.firebaseapp.com',
    storageBucket: 'qlchitieu-30b85.firebasestorage.app',
    measurementId: 'G-Z85C71116L',
  );
}
